language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t jayeshkhazari/dockerspringboot .


deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-243539042978"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

